Release v4.4.0
DataDog/datadog-go pull request #184
Opened 2021-02-10 09:59 UTC by gbbr

2021-02-10 10:01 UTC, hush-hush requested changes

2021-02-10 10:01 UTC, hush-hush commented on CHANGELOG.md
> +* [BUGFIX] Fix a problem with multi-metric aggregation. See [#181][].
```suggestion
* [BETA][BUGFIX] Fix multi-metric aggregation when packing different metrics in the same packet. See [#181][].
```

2021-02-10 10:01 UTC, hush-hush commented on CHANGELOG.md
> +# 4.4.0 / 2021-01-10
```suggestion
# 4.4.0 / 2021-02-10
```

2021-02-11 13:49 UTC, gbbr commented
@hush-hush I think we're good to go now

2021-02-12 10:36 UTC, hush-hush approved these changes

2021-02-12 10:36 UTC, merged